JuliaReach/ClosedLoopReachability.jl

- models/Sherlock-Benchmark-10/Sherlock-Benchmark-10.jl
> Sherlock-Benchmark-10 (Unicycle Car Model)

- docs/generate.jl
> #20 - Fix autogenerated examples

- models/ACC/ACC.jl
> #26 - Fix specs in ACC

- models/ACC/ACC.jl
- models/Non-linear Cart-Pole/Cart-Pole.jl
- models/Sherlock-Benchmark-10/Sherlock-Benchmark-10.jl
- models/Sherlock-Benchmark-7/Sherlock-Benchmark-7.jl
- models/Sherlock-Benchmark-9/Sherlock-Benchmark-9.jl
> #24 - Add links to generated notebooks

- models/ACC/ACC.jl
- models/Non-linear Cart-Pole/Cart-Pole.jl
- models/Sherlock-Benchmark-10/Sherlock-Benchmark-10.jl
- models/Sherlock-Benchmark-7/Sherlock-Benchmark-7.jl
> #25 - Fix References in models

- models/Sherlock-Benchmark-9/Sherlock-Benchmark-9.jl
> #32 - Add specs for TORA

- Project.toml
- docs/generate.jl
- docs/make.jl
Commits
1. update dependencies (needed to check out this package locally)
2. remove broken model from build (#82)
3. copy over `.nnet` files for `Literate` processing
4. remove broken model from build (algorithm crashes)
> Update dependencies and fix build

- models/Sherlock-Benchmark-10-Unicycle/Sherlock-Benchmark-10-Unicycle.jl
- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA.jl
- src/nnops.jl
- src/problem.jl
- src/simulate.jl
- src/solve.jl
> #91 - Add normalization of control inputs to models

- src/utils.jl
Closes #96.
```julia
using NeuralNetworkAnalysis, DifferentialEquations, Plots
n = 2;
m = 1;
T = 0.2;
period = T/10;
problems = NeuralNetworkAnalysis.toy_models(n, m; period=period);
vars = (0, 1);
plots = Plots.Plot[];
for cp in problems
simulations, _, _ = simulate(cp, T=T; include_vertices=true);
alg = TMJets(abs_tol=1e-10, orderT=8, orderQ=3);
alg_nn = Ai2();
sol = NeuralNetworkAnalysis.solve(cp, T=T, alg_nn=alg_nn, alg=alg);
x = vars[1] == 0 ? "t" : "x$(vars[1])";
y = vars[2] == 0 ? "t" : "x$(vars[2])";
p = plot(sol, vars=vars, xlab=x, ylab=y)
for simulation in simulations
plot!(simulation, vars=vars)
end
push!(plots, p)
end
plot(plots...)
```
> #96 - Parametric family of toy models with random dynamics

- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA.jl
- src/init_DifferentialEquations.jl
- src/simulate.jl
Closes #101.
I do not particularly like the name `inputs` because we have control inputs and nondeterministic inputs. Is there a better word?
> #101 - Let simulate return a struct

- src/NeuralNetworkAnalysis.jl
- src/nnops.jl
> Add VertexSolver

- src/nnops.jl
- src/utils.jl
> Add sampler solver

- src/NeuralNetworkAnalysis.jl
- src/nnops.jl
I played around with this idea but it turns out to be not good, at least in combination with a `BoxSolver`. I think it is still nice to have, though.
> Add SplitSolver

- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA.jl
The docs have 60 MB because of this model. With this PR, checking out the newest changes is a lot faster.
> Deactivate plots in TORA model

- docs/Project.toml
- models/Sherlock-Benchmark-7/Sherlock-Benchmark-7.jl
- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA.jl
Undo #131 and instead create small plots.
(temporary example [here](https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/gh-pages/previews/PR133/models/Sherlock-Benchmark-9-TORA.ipynb))
> Use PNG plots in docs

- src/init.jl
- src/init_DifferentialEquations.jl
- src/init_DifferentialEquations_Plots.jl
The plotting function in #135 did not work (I had not actually tried it out). The problem was that `Plots` functions require `Plots`.
> Fix plotting function

- src/simulate.jl
> Allow T that is not a multiple of period in simulations

- src/init_DifferentialEquations_Plots.jl
> #149 - Add label for plot_simulation!

- src/nnops.jl
Closes #123.
I can explain the idea. Unfortunately this turns out to be numerically inconsistent and so it is useless.
> #123 - Make VertexSolver sound

- src/nnops.jl
> #120 - Add vertices to SampledApprox

- models/Double-Pendulum/Double-Pendulum.jl
This part of #165 was not intended,
> Undo unintended changes

- Project.toml
- src/NeuralNetworkAnalysis.jl
- src/nnops.jl
- src/problem.jl
- src/simulate.jl
- src/solve.jl
- test/black_box_toy_model.jl
- test/runtests.jl
> Add black-box network

- src/setops.jl
- src/solve.jl
> Refactoring of solve; remove unused method and argument

- src/setops.jl
- src/solve.jl
Requires ~https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/499~ a new release of `ReachabilityAnalysis` (after v0.14.6).
> pass generator removal option

- src/solve.jl
First step for #183.
Changes:
- outsource the loop to a new function
- store the result in a waiting list
- use a vector for the time steps
> Refactor solve

- models/Airplane/Airplane.jl
[Output](https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/gh-pages/previews/PR197/models/Airplane.ipynb)
> Polish Airplane model

- models/ACC/ACC.jl
[Output from other PR](https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/gh-pages/previews/PR187/models/ACC.ipynb)
[Output after the build finishes here](https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/gh-pages/previews/PR199/models/ACC.ipynb)
> Polish ACC model

- models/VertCAS/VertCAS.jl
[Output](https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/gh-pages/previews/PR200/models/VertCAS.ipynb)
> Polish VertCAS model

- models/Double-Pendulum/Double-Pendulum.jl
- src/problem.jl
The `Specification` struct in the first commit is just used as a wrapper (because the model is written as a function of an argument to choose the controller setting, and the specification depends on that).
> Polish DoublePendulum model

- src/NeuralNetworkAnalysis.jl
- src/nnops.jl
- src/problem.jl
- src/setops.jl
- src/solve.jl
- src/split.jl
> #183 - Splitting

- Project.toml
- models/Sherlock-Benchmark-10-Unicycle/Sherlock-Benchmark-10-Unicycle.jl
- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA.jl
- src/NeuralNetworkAnalysis.jl
- src/init.jl
- src/nnops.jl
- src/problem.jl
- src/simulate.jl
- src/solve.jl
- test/black_box_toy_model.jl
Closes #106.
Closes #188.
Closes #204.
> CommonSolve, Normalization -> Postprocessing, AbstractNetwork

- src/setops.jl
> #210 - Generalize TM reconstructor

- models/ACC/ACC.jl
- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA.jl
- models/Single-Pendulum/Single-Pendulum.jl
- src/solve.jl
> Use TaylorModelReconstructor by default

- src/setops.jl
> #221 - Generalize input set in multi-dimensional controls

- .github/workflows/docs.yml
- src/init_DifferentialEquations_Plots.jl
When I pass `vars=[1, 2]` I get a different plot compared to `vars=(1, 2)`.
> Fix plot_simulation! when passing a vector of variables

- models/Sherlock-Benchmark-10-Unicycle/Sherlock-Benchmark-10-Unicycle.jl
test for https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/pull/238
> Update references for unicycle model

- Project.toml
- src/init.jl
- src/utils.jl
> #213 - Make MAT an optional dependency

- src/utils.jl
> Fix ONNX parser (transposed W)

- models/Airplane/Airplane.jl
- models/Double-Pendulum/Double-Pendulum.jl
> #219 - Use TMJets21b for Double-Pendulum

- Project.toml
- src/init.jl
- src/nnops.jl
- src/setops.jl
- src/solve.jl
> #285 - Remove dependencies reexported by ReachabilityAnalysis

- models/ACC/ACC.jl
- models/Airplane/Airplane.jl
- models/Double-Pendulum/Double-Pendulum.jl
- models/Sherlock-Benchmark-10-Unicycle/Sherlock-Benchmark-10-Unicycle.jl
- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA-ReluTanh.jl
- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA-Sigmoid.jl
- models/Sherlock-Benchmark-9-TORA/Sherlock-Benchmark-9-TORA.jl
- models/Single-Pendulum/Single-Pendulum.jl
- src/init_DifferentialEquations.jl
- src/problem.jl
- src/simulate.jl
- src/solve.jl
- src/utils.jl
- test/black_box_toy_model.jl
Closes #262.
This is a breaking change.
> #262 - rename _vars keys and getters

- models/VertCAS/VertCAS.jl
- src/ClosedLoopReachability.jl
- src/nnops.jl
- src/solve.jl
- src/utils.jl
Closes #286.
This is a breaking change.
> #286 - Rename forward_network -> forward

- src/solve.jl
> #40 - Store control signals with corresponding flowpipe

- models/Airplane/Airplane.jl
The fix in #269 was only partially correct.
> Fix typo in Airplane dynamics

- test/black_box_toy_model.jl
- test/runtests.jl
Apparently I forgot to format the tests in #334.
> Format test code

- .github/workflows/CompatHelper.yml
- docs/Project.toml
- docs/make.jl
Also add bounds for all packages in the docs script.
> Support/use Documenter v1

- src/init_DifferentialEquations.jl
- src/simulate.jl
> Avoid `using .DifferentialEquations`

- docs/generate.jl
- models/ACC/ACC.jl
- models/Airplane/Airplane.jl
- models/AttitudeControl/AttitudeControl.jl
- models/InvertedPendulum/InvertedPendulum.jl
- models/InvertedTwoLinkPendulum/InvertedTwoLinkPendulum.jl
- models/Quadrotor/Quadrotor.jl
- models/SpacecraftDocking/SpacecraftDocking.jl
- models/TORA/TORA.jl
- models/Unicycle/Unicycle.jl
- models/VerticalCAS/VerticalCAS.jl
Build time with notebooks: 31m 24s
Build time without notebooks: 21m 17s
> Revise Literate script and deactivate notebook generation

- .github/workflows/documentation.yml
- docs/make.jl
> Fix CI script for documentation deployment
